default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: WatchGrabber_development

test:
  <<: *default
  database: WatchGrabber_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] || 'WatchGrabber_production' %>
