:concurrency: 2
:max_retries: 3
:queues:
  - critical
  - default
  - checking
  - parsing
  - low
:limits:
  parsing: 1
:schedule:
  checking_job:
    queue: checking
    class: CheckingJob
    cron: '*/3 * * * * *'
