name: Rails Specs
on: [push]
jobs:
  rspec-test:
    name: Rubocop/RSpec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.2
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

      redis:
        image: redis:5.0.7
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install postgres client
        run: sudo apt-get install libpq-dev

      - name: Install dependencies
        run: |
          gem install bundler
          bundler install

      - name: Run Rubocop
        run: |
          bundle exec rubocop

      - name: Run RSpec
        run: |
          bundle exec rake db:create db:schema:load
          COVERAGE=true bundle exec rspec  --require rails_helper
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          REDIS_URL: redis://localhost:6379/0
