name: Rubocop
on: push

jobs:
  rubocop:
    runs-on: ubuntu-latest

    env:
      RUBY_VERSION: 3.0.0

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install dependencies
        run: |
          gem install bundler
          bundler install

      - name: Run Rubocop
        run: bundle exec rubocop
